#!/bin/bash

set -e

REC_DIR=$1
LIG_DIR=$2
PRIORITY=$3
if [ "x$REC_DIR" = "x" -o "x$LIG_DIR" = "x" ]; then
    echo "Please specify the receptor directory, and the ligand directory. Example:" 1>&2
    echo "  ./submit inputs/rec inputs/lig" 1>&2
    echo 1>&2
    echo "A third optional argument is for priority of the workflow. Example" 1>&2
    echo "  ./submit inputs/rec inputs/lig 100000" 1>&2
    exit 1
fi

TOP_DIR=`pwd`

RUN_ID=`/bin/date +'%F_%H%M%S'`

# unique directory for this run
RUN_DIR=/stash/user/$USER/workflows/vina-$RUN_ID

if [ "x$PRIORITY" = "x" ]; then
    TS=`date +'%Y%m%d'`
    PRIORITY=$((20200000 - $TS))
fi

# expand the dirs
REC_DIR=`cd $REC_DIR && pwd`
LIG_DIR=`cd $LIG_DIR && pwd`

mkdir -p $RUN_DIR
cd $RUN_DIR

echo " ** "
echo " ** Run dir is $RUN_DIR"
echo " ** "

# move to the run dir for dax generation
cp -r $TOP_DIR/* $RUN_DIR/
cd $RUN_DIR/

# generate the dax
export PYTHONPATH=`pegasus-config --python`
./dax-generator.py $RUN_ID $RUN_DIR $REC_DIR $LIG_DIR $PRIORITY

# create the site catalog
cat >sites.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<sitecatalog xmlns="http://pegasus.isi.edu/schema/sitecatalog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pegasus.isi.edu/schema/sitecatalog http://pegasus.isi.edu/schema/sc-4.0.xsd" version="4.0">

    <site handle="local" arch="x86_64">
        <directory type="shared-scratch" path="$RUN_DIR/scratch">
            <file-server operation="all" url="file://$RUN_DIR/scratch"/>
        </directory>
        <directory type="local-storage" path="$RUN_DIR/outputs">
            <file-server operation="all" url="file://$RUN_DIR/outputs"/>
        </directory>
        <profile namespace="env" key="PATH">$PATH</profile>
    </site>

    <site handle="condorpool" arch="x86_64">
        <profile namespace="pegasus" key="style">condor</profile>
        <profile namespace="condor" key="universe">vanilla</profile>
        <profile namespace="condor" key="requirements">OSGVO_OS_STRING == "RHEL 6" &amp;&amp; HAS_MODULES == True</profile>
    </site>

</sitecatalog>
EOF

# plan and submit the  workflow
pegasus-plan \
    --conf pegasus.conf \
    --dir $RUN_DIR/run \
    --relative-dir $RUN_ID \
    --sites condorpool \
    --output-site local \
    --dax dax-top.xml \
    --submit \
    2>&1 | tee submit.log


